# Generated by Django 4.2.3 on 2023-07-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Physician', 'Physician'), ('Orthopedic', 'Orthopedic'), ('Gynecology', 'Gynecology'), ('Pediatric', 'Pediatric'), ('Cardiologist', 'Cardiologist'), ('Dental', 'Dental'), ('ENT', 'ENT'), ('Eye Care', 'Eye Care'), ('General Surgeon', 'General Surgeon'), ('Anesthesia', 'Anesthesia'), ('Pulmonary & Sleep Med', 'Pulmonary & Sleep Med'), ('Pathology', 'Pathology'), ('Plastic & Cosmetic', 'Plastic & Cosmetic'), ('Psychiatric', 'Psychiatric'), ('Physiotherapist', 'Physiotherapist')], max_length=100),
        ),
    ]
